WIP:Remove code duplication for rln nde cloning

diff --git a/.github/workflows/iris-wallet-desktop.yml b/.github/workflows/iris-wallet-desktop.yml
--- a/.github/workflows/iris-wallet-desktop.yml
+++ b/.github/workflows/iris-wallet-desktop.yml
@@ -2,8 +2,8 @@ name: Iris Wallet Desktop CI
 
 on:
   push:
-    tags:
-      - '*' # Trigger this workflow on any tag push
+    branches:
+      - 'gh-action-code-duplication' 
 
 jobs:
   build-iris-wallet-desktop-linux:
@@ -15,25 +15,25 @@ jobs:
           submodules: true # Include submodules in the checkout
           fetch-depth: 1 # Fetch the latest commit only
 
-      - name: Validate Tag and Code Version
-        run: |
-          TAG_VERSION=$(git describe --tags)
-          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
+      # - name: Validate Tag and Code Version
+      #   run: |
+      #     TAG_VERSION=$(git describe --tags)
+      #     echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
 
-          # Extract version from tag
-          echo "Tag version: $TAG_VERSION"
+      #     # Extract version from tag
+      #     echo "Tag version: $TAG_VERSION"
 
-          # Extract version from code
-          CODE_VERSION=$(grep '__version__' ./src/version.py | awk -F'=' '{print $2}' | tr -d ' "' | xargs)
-          echo "Code version: $CODE_VERSION"
+      #     # Extract version from code
+      #     CODE_VERSION=$(grep '__version__' ./src/version.py | awk -F'=' '{print $2}' | tr -d ' "' | xargs)
+      #     echo "Code version: $CODE_VERSION"
 
-          # Compare the tag and code version
-          if [ "$TAG_VERSION" != "$CODE_VERSION" ]; then
-            echo "❌ Tag version ($TAG_VERSION) does not match code version ($CODE_VERSION)."
-            exit 1
-          else
-            echo "✅ Tag version matches code version."
-          fi
+      #     # Compare the tag and code version
+      #     if [ "$TAG_VERSION" != "$CODE_VERSION" ]; then
+      #       echo "❌ Tag version ($TAG_VERSION) does not match code version ($CODE_VERSION)."
+      #       exit 1
+      #     else
+      #       echo "✅ Tag version matches code version."
+      #     fi
 
       - name: Install Rust Programming Environment
         run: |
@@ -53,24 +53,29 @@ jobs:
           sudo apt-get install ruby-dev build-essential libgirepository1.0-dev python3-dev -y && sudo gem i fpm -f
           sudo apt-get update && sudo apt-get install -y libfuse2 # Required for AppImage creation
 
-      - name: Clone rgb-lightning-node repository with submodules
-        run: |
-          CURRENT_RLN_NODE_COMMIT=$(grep 'CURRENT_RLN_NODE_COMMIT' ./src/utils/constant.py | awk -F'=' '{print $2}' | tr -d ' "' | xargs)
+      # - name: Clone rgb-lightning-node repository with submodules
+      #   run: |
+      #     CURRENT_RLN_NODE_COMMIT=$(grep 'CURRENT_RLN_NODE_COMMIT' ./src/utils/constant.py | awk -F'=' '{print $2}' | tr -d ' "' | xargs)
 
-          if [ -z "$CURRENT_RLN_NODE_COMMIT" ]; then
-            echo "❌ Error: CURRENT_RLN_NODE_COMMIT is empty or not found in constant.py"
-            exit 1
-          fi
+      #     if [ -z "$CURRENT_RLN_NODE_COMMIT" ]; then
+      #       echo "❌ Error: CURRENT_RLN_NODE_COMMIT is empty or not found in constant.py"
+      #       exit 1
+      #     fi
 
-          git clone https://github.com/RGB-Tools/rgb-lightning-node --recurse-submodules --shallow-submodules
-          cd rgb-lightning-node
+      #     git clone https://github.com/RGB-Tools/rgb-lightning-node --recurse-submodules --shallow-submodules
+      #     cd rgb-lightning-node
 
-          if ! git checkout ${CURRENT_RLN_NODE_COMMIT}; then
-            echo "❌ Error: Failed to checkout commit ${CURRENT_RLN_NODE_COMMIT}"
-            exit 1
-          fi
+      #     if ! git checkout ${CURRENT_RLN_NODE_COMMIT}; then
+      #       echo "❌ Error: Failed to checkout commit ${CURRENT_RLN_NODE_COMMIT}"
+      #       exit 1
+      #     fi
 
-          git submodule update --init --recursive
+      #     git submodule update --init --recursive
+
+      - name: Call Clone RGB Node reusable workflow
+        uses: ./.github/workflows/clone-rln.yml
+        with:
+          os: ubuntu-22.04
 
       - name: Build the rgb-lightning-node binary
         working-directory: rgb-lightning-node
